modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="gmsb"
version="0.0.1"
displayName="Grimm's Mod Base"
displayURL="https://www.gsdistance.org"
logoFile="logo.png"
credits="Grimm, tyuXX, tyuYY, tyuZZ"
authors="Grimm"
description="Grimm's Mod, now as a series."

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.gmsb]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.137,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.gmsb]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration